### ISSUE TITLE
gatewaysv2: bootstrapping txfee+marker_value for gatewaysdeposit

### ISSUE THREAD

**Issue by Alrighttt** [Mixa84/komodo#69]
An issue with gateways as it stands is that a user is required to already have at least a balance of txfee+CC_MARKER_VALUE in order to create a gatewaysdeposit transaction. 

I believe of a sensible way of getting rid of this requirement would be to set the CC_MARKER_VALUE for gateways deposit to 0 sats and to subtract the txfee from the deposit amount.

**Comment by Mixa84** [comment]
When using gateway with tokens, it is not difficult to get some funds to be able to issue a gatewaysdeposit tx. User could either mine the chain, or faucet could be setup on that chain to give small amount of funds for entry users.

In importgateway, which gives coins on deposit, that tx is import type and it is processed without txfee and there are no markers because import txes hav tombstones to identify if they exists already so there will be no problem for new users to enter to the chain.
